apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ngd-k3s-example
  namespace: default
  labels:
    name: ngd-k3s-example
spec:
  selector:
    matchLabels:
      name: ngd-k3s-example
  template:
    metadata:
      labels:
        name: ngd-k3s-example
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - arm64
      containers:
        - name: ngd-k3s-example
          image: 10.1.1.1:27443/ngd-k3s-example:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 5500
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
