apiVersion: v1
kind: Service
metadata:
  name: ngd-k3s-example-svc
  namespace: default
spec:
  type: LoadBalancer
  selector:
    name: ngd-k3s-example
  ports:
    - protocol: TCP
      port: 5500
      targetPort: 5500
