apiVersion: v1
kind: Service
metadata:
  name: ngd-k3s-example-svc
  namespace: default
spec:
  selector:
    app: ngd-k3s-example
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  clusterIP: None
  type: ClusterIP
